# Generated by Django 5.1.6 on 2025-05-03 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_carbonfootprint_croprecommendationhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarbonFootprint',
        ),
    ]
