# Generated by Django 5.1.6 on 2025-05-03 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_delete_carbonfootprint'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonFootprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_emission', models.FloatField()),
                ('grocery_bill', models.FloatField()),
                ('vehicle_distance', models.FloatField()),
                ('waste_bags', models.IntegerField()),
                ('digital_time', models.FloatField()),
                ('clothes_purchased', models.IntegerField()),
                ('do_you_smoke', models.BooleanField()),
                ('recycling_habit', models.BooleanField()),
                ('buy_local_produce', models.BooleanField()),
                ('use_public_transport', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
