# Generated by Django 5.1.6 on 2025-05-05 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_carbonfootprint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarbonFootprint',
        ),
    ]
